"""add github fields to users

Revision ID: 45ce15433eee
Revises: f5fa7f2f5e7f
Create Date: 2026-04-13 17:25:02.095177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ce15433eee'
down_revision: Union[str, Sequence[str], None] = 'f5fa7f2f5e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('github_login', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'github_email')
    op.drop_column('users', 'github_login')
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
