"""update  users4

Revision ID: 553d550d6147
Revises: f3306b1743b6
Create Date: 2026-04-17 15:46:33.925227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553d550d6147'
down_revision: Union[str, Sequence[str], None] = 'f3306b1743b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
