"""add 2fa fields to users

Revision ID: f5fa7f2f5e7f
Revises: 424abbb2b945
Create Date: 2026-04-13 14:50:12.807505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5fa7f2f5e7f'
down_revision: Union[str, Sequence[str], None] = '424abbb2b945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column(
        'users',
        sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_2fa_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
